/**
 * Version constant generated by the build at build time.
 * This file imports from version.generated.ts, which is created by the build process.
 * Falls back to 'development' if the generated file doesn't exist
 */
let VERSION: string;

try {
  // Try to import from the generated build metadata when it exists.
  const generated = await import("./version.generated.ts");
  VERSION = generated.VERSION;
} catch {
  // Fallback to 'development' if generated file doesn't exist
  VERSION = "development";
}

export { VERSION };
