/**
 * Version constant generated by the build at build time.
 * version.generated.ts is produced by the codegen build step; a missing file
 * is a build-time error rather than a silent runtime fallback.
 */
export { VERSION } from "./version.generated.ts";
