#!/usr/bin/env -S deno run -A

/**
 * Embeds the compiled WASM artifacts directly into TypeScript source.
 *
 * This script reads the debug and release artifacts from `wasm/` and produces
 * `lib/evaluator/arenaWasm.embedded.ts`, enabling environments without a
 * filesystem or network (e.g. bundled CLI builds) to instantiate the arena
 * evaluator.
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const wasmDir = join(repoRoot, "wasm");
const outputFile = join(repoRoot, "lib", "evaluator", "arenaWasm.embedded.ts");

function bytesToBase64(bytes: Uint8Array): string {
  const chunkSize = 0x8000;
  let binary = "";
  for (let i = 0; i < bytes.length; i += chunkSize) {
    const chunk = bytes.subarray(i, i + chunkSize);
    binary += String.fromCharCode(...chunk);
  }
  return btoa(binary);
}

function chunkString(str: string, size: number): string[] {
  const chunks: string[] = [];
  for (let i = 0; i < str.length; i += size) {
    chunks.push(str.slice(i, i + size));
  }
  return chunks;
}

const releasePath = join(wasmDir, "release.wasm");
let releaseBytes: Uint8Array;
try {
  releaseBytes = await Deno.readFile(releasePath);
} catch (error) {
  throw new Error(
    `Failed to read ${releasePath}. Make sure the WASM artifacts exist before embedding.`,
    { cause: error },
  );
}
const releaseBase64 = bytesToBase64(releaseBytes);
console.log(
  `Embedded release.wasm (${releaseBytes.length.toLocaleString()} bytes)`,
);

function formatBase64Const(name: string, base64: string): string {
  const chunks = chunkString(base64, 128);
  const joined = chunks.map((chunk) => `  "${chunk}"`).join(" +\n");
  return `const ${name} =\n${joined};\n`;
}

const fileContents = `/**
 * AUTO-GENERATED FILE: DO NOT EDIT.
 *
 * This file is generated by \`deno run -A scripts/embed-wasm.ts\` and embeds the
 * compiled WASM artifacts into the TypeScript bundle so environments without a
 * filesystem or network (e.g. Deno bundle / compile) can instantiate the arena
 * evaluator.
 */

${formatBase64Const("releaseBase64", releaseBase64)}

let releaseCache: Uint8Array | null = null;

function base64ToUint8Array(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

export function getEmbeddedReleaseWasm(): Uint8Array {
  if (releaseCache) return releaseCache;
  releaseCache = base64ToUint8Array(releaseBase64);
  return releaseCache;
}
`;

await Deno.writeTextFile(outputFile, fileContents);
console.log(`Wrote embedded WASM module: ${outputFile}`);
