import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import process from "node:process";

const normalize = (s) => s.replace(/\r\n/g, "\n");

function buildTsContent(version) {
  return `/**
 * This file is automatically generated by the build process.
 * Do not edit it manually.
 */
export const VERSION = "${version}";
`;
}

function buildJsrJson(pkg) {
  const jsrJson = {
    name: pkg.name,
    version: pkg.version,
    license: pkg.license,
    exports: pkg.exports,
    publish: pkg.jsr?.publish || {
      include: pkg.files || [],
    },
    compilerOptions: {
      strict: true,
      lib: ["ESNext", "dom"],
      types: ["@types/node"],
    },
    imports: {
      "random-seed": `npm:random-seed@${pkg.dependencies["random-seed"]}`,
      "ts-morph": `npm:ts-morph@${pkg.dependencies["ts-morph"]}`,
      "@types/node": `npm:@types/node@${pkg.devDependencies["@types/node"]}`,
    },
  };

  return JSON.stringify(jsrJson, null, 2) + "\n";
}

async function main() {
  const args = getArgs();

  if (args.debugPaths) {
    console.log("Debug Paths:");
    console.log(`  process.cwd(): ${process.cwd()}`);
    console.log(`  process.execPath: ${process.execPath}`);
    console.log(`  --root: ${args.root}`);
    console.log(`  --package-json: ${args.packageJson}`);
    console.log(`  --ts-out: ${args.tsOut}`);
    if (args.jsrJson) console.log(`  --jsr-json: ${args.jsrJson}`);
  }

  const root = resolve(args.root || ".");
  const pkgJsonPath = args.packageJson
    ? resolve(args.packageJson)
    : join(root, "package.json");

  const pkg = JSON.parse(await readFile(pkgJsonPath, "utf8"));
  const version = pkg.version;

  if (args.verify) {
    let failed = false;

    if (args.tsOut) {
      const tsPath = resolve(args.tsOut);
      const expectedTsContent = buildTsContent(version);
      const actualTsContent = await readFile(tsPath, "utf8").catch(() => null);
      if (actualTsContent === null) {
        console.error(`ERROR: ${tsPath} does not exist`);
        failed = true;
      } else if (normalize(actualTsContent) !== normalize(expectedTsContent)) {
        console.error(
          `ERROR: ${tsPath} is out of sync with package.json metadata`,
        );
        failed = true;
      }
    }

    if (args.jsrJson) {
      const jsrJsonPath = resolve(args.jsrJson);
      const expectedJsrJsonContent = buildJsrJson(pkg);
      const actualJsrContent = await readFile(jsrJsonPath, "utf8").catch(
        () => null,
      );
      if (actualJsrContent === null) {
        console.error(`ERROR: ${jsrJsonPath} does not exist`);
        failed = true;
      } else if (
        normalize(actualJsrContent) !== normalize(expectedJsrJsonContent)
      ) {
        console.error(
          `ERROR: ${jsrJsonPath} is out of sync with package.json metadata`,
        );
        failed = true;
      }
    }

    if (failed) {
      process.exit(1);
    }
  } else {
    const writes = [];
    if (args.tsOut) {
      const tsPath = resolve(args.tsOut);
      writes.push(writeFile(tsPath, buildTsContent(version), "utf8"));
    }
    if (args.jsrJson) {
      const jsrJsonPath = resolve(args.jsrJson);
      writes.push(writeFile(jsrJsonPath, buildJsrJson(pkg), "utf8"));
    }

    await Promise.all(writes);

    console.log(
      `Successfully processed version metadata for version: ${version}`,
    );
  }
}

function getArgs() {
  const args = {};
  for (let i = 0; i < process.argv.length; i++) {
    const arg = process.argv[i];
    if (arg === "--root") args.root = process.argv[++i];
    if (arg === "--package-json") args.packageJson = process.argv[++i];
    if (arg === "--ts-out") args.tsOut = process.argv[++i];
    if (arg === "--jsr-json") args.jsrJson = process.argv[++i];
    if (arg === "--verify") args.verify = true;
    if (arg === "--debug-paths") args.debugPaths = true;
  }
  return args;
}

await main();
