import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import process from "node:process";

function resolveRequired(val, name) {
  if (!val) {
    console.error(`ERROR: Missing required argument ${name}`);
    process.exit(1);
  }
  return resolve(val);
}

const normalize = (s) => s.replace(/\r\n/g, "\n");

async function main() {
  const args = getArgs();

  if (args.debugPaths) {
    console.log("Debug Paths:");
    console.log(`  process.cwd(): ${process.cwd()}`);
    console.log(`  process.execPath: ${process.execPath}`);
    console.log(`  --root: ${args.root}`);
    console.log(`  --package-json: ${args.packageJson}`);
    console.log(`  --ts-out: ${args.tsOut}`);
  }

  const root = resolve(args.root || ".");
  const pkgJsonPath = args.packageJson
    ? resolve(args.packageJson)
    : join(root, "package.json");

  const pkg = JSON.parse(await readFile(pkgJsonPath, "utf8"));
  const version = pkg.version;

  // 1. Construct expected version.generated.ts content
  const expectedTsContent = `/**
 * This file is automatically generated by the build process.
 * Do not edit it manually.
 */
export const VERSION = "${version}";
`;

  // 2. Construct expected jsr.json content
  const expectedJsrJson = {
    name: pkg.name,
    version: pkg.version,
    license: pkg.license,
    exports: pkg.exports,
    publish: pkg.jsr?.publish || {
      include: pkg.files || [],
    },
    compilerOptions: {
      strict: true,
      lib: ["ESNext", "dom"],
      types: ["@types/node"],
    },
    imports: {
      "random-seed": `npm:random-seed@${pkg.dependencies["random-seed"]}`,
      "ts-morph": `npm:ts-morph@${pkg.dependencies["ts-morph"]}`,
      "@types/node": `npm:@types/node@${pkg.devDependencies["@types/node"]}`,
    },
  };
  const expectedJsrJsonContent = JSON.stringify(expectedJsrJson, null, 2) + "\n";

  const tsPath = args.tsOut
    ? resolve(args.tsOut)
    : join(root, "lib/shared/version.generated.ts");
  const jsrJsonPath = join(root, "jsr.json");

  if (args.verify) {
    // STRICT VERIFICATION MODE
    let failed = false;

    // Verify version.generated.ts
    const actualTsContent = await readFile(tsPath, "utf8").catch(() => null);
    if (actualTsContent === null) {
      console.error(`ERROR: ${tsPath} does not exist`);
      failed = true;
    } else if (normalize(actualTsContent) !== normalize(expectedTsContent)) {
      console.error(`ERROR: ${tsPath} is out of sync with package.json metadata`);
      failed = true;
    }

    // Verify jsr.json
    const actualJsrContent = await readFile(jsrJsonPath, "utf8").catch(() => null);
    if (actualJsrContent === null) {
      console.error(`ERROR: ${jsrJsonPath} does not exist`);
      failed = true;
    } else if (normalize(actualJsrContent) !== normalize(expectedJsrJsonContent)) {
      console.error(`ERROR: ${jsrJsonPath} is out of sync with package.json metadata`);
      failed = true;
    }

    if (failed) {
      process.exit(1);
    }
  } else {
    // GENERATION MODE
    await writeFile(tsPath, expectedTsContent, "utf8");
    await writeFile(jsrJsonPath, expectedJsrJsonContent, "utf8");

    console.log(
      `Successfully processed version metadata for version: ${version}`,
    );
  }
}

function getArgs() {
  const args = {};
  for (let i = 0; i < process.argv.length; i++) {
    const arg = process.argv[i];
    if (arg === "--root") args.root = process.argv[++i];
    if (arg === "--package-json") args.packageJson = process.argv[++i];
    if (arg === "--ts-out") args.tsOut = process.argv[++i];
    if (arg === "--verify") args.verify = true;
    if (arg === "--debug-paths") args.debugPaths = true;
  }
  return args;
}

await main();
