/**
 * Version and JSR configuration generation script
 *
 * This script reads the version from package.json and generates:
 * 1. lib/shared/version.generated.ts (static version metadata)
 * 2. jsr.json (JSR configuration with the correct version)
 */

import { writeFile } from "node:fs/promises";
import { getRepoVersion } from "./repoNode.ts";

async function main() {
  try {
    const version = getRepoVersion();

    if (!version) {
      console.error("Version not found in package.json");
      process.exit(1);
    }

    // 1. Generate version.generated.ts
    const versionContent = `/**
 * This file is automatically generated by the build process.
 * Do not edit it manually.
 */
export const VERSION = "${version}";
`;
    await writeFile("lib/shared/version.generated.ts", versionContent, "utf8");

    // 2. Generate jsr.json
    const jsrConfig = {
      name: "@maxdeliso/typed-ski",
      version: version,
      license: "MIT",
      exports: {
        ".": "./lib/index.ts",
        "./bin/tripc": "./bin/tripc.ts",
      },
      publish: {
        include: [
          "README.md",
          "SECURITY.md",
          "lib/**",
          "bin/**",
          "dist/**",
          "wasm/release.wasm",
        ],
        exclude: [
          "!lib/**/*.generated.ts",
          "!lib/evaluator/arenaHeader.generated.ts",
        ],
      },
      compilerOptions: {
        strict: true,
        lib: ["dom"],
        types: ["@types/node"],
      },
      imports: {
        "@types/node": "npm:@types/node@^25.0.10",
        "random-seed": "npm:random-seed@0.3.0",
        "ts-morph": "npm:ts-morph@^25.0.0",
      },
    };

    await writeFile("jsr.json", JSON.stringify(jsrConfig, null, 2), "utf8");

    console.log(
      `Successfully generated version metadata and jsr.json with version: ${version}`,
    );
  } catch (error) {
    console.error(`Error generating version: ${error}`);
    process.exit(1);
  }
}

await main();
