/**
 * Version generation script
 *
 * This script reads the version from deno.jsonc and generates the static
 * version metadata imported by lib/shared/version.ts.
 */

const denoJson = await Deno.readTextFile("deno.jsonc");
const json = JSON.parse(denoJson);
const version = json.version;

if (!version) {
  console.error("Version not found in deno.jsonc");
  Deno.exit(1);
}

const content = `/**
 * This file is automatically generated by the build process.
 * Do not edit it manually.
 */
export const VERSION = "${version}";
`;

await Deno.writeTextFile("lib/shared/version.generated.ts", content);

console.log(`Successfully generated version metadata with version: ${version}`);
