import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import process from "node:process";

function resolveRequired(val, name) {
  if (!val) {
    console.error(`ERROR: Missing required argument ${name}`);
    process.exit(1);
  }
  return resolve(val);
}

const normalize = (s) => s.replace(/\r\n/g, "\n");

async function main() {
  const args = getArgs();

  if (args.debugPaths) {
    console.log("Debug Paths:");
    console.log(`  process.cwd(): ${process.cwd()}`);
    console.log(`  process.execPath: ${process.execPath}`);
    console.log(`  --package-json: ${args.packageJson}`);
    console.log(`  --ts-out: ${args.tsOut}`);
    console.log(`  --jsr-json: ${args.jsrJson}`);
  }

  const pkgJsonPath = resolveRequired(args.packageJson, "--package-json");
  const pkg = JSON.parse(await readFile(pkgJsonPath, "utf8"));
  const version = pkg.version;

  const versionContent = `/**
 * This file is automatically generated by the build process.
 * Do not edit it manually.
 */
export const VERSION = "${version}";
`;

  if (args.tsOut) {
    const tsPath = resolve(args.tsOut);
    if (args.verify) {
      const existing = await readFile(tsPath, "utf8").catch(() => "");
      if (normalize(existing) !== normalize(versionContent)) {
        console.error(
          `ERROR: ${args.tsOut} is out of sync with package.json version ${version}`,
        );
        process.exit(1);
      }
    } else {
      await writeFile(tsPath, versionContent, "utf8");
    }
  }

  // Update jsr.json if requested
  if (args.jsrJson) {
    const jsrJsonPath = resolve(args.jsrJson);
    const jsrJson = JSON.parse(await readFile(jsrJsonPath, "utf8"));
    if (args.verify) {
      if (jsrJson.version !== version) {
        console.error(
          `ERROR: ${args.jsrJson} version ${jsrJson.version} is out of sync with package.json version ${version}`,
        );
        process.exit(1);
      }
    } else {
      jsrJson.version = version;
      await writeFile(
        jsrJsonPath,
        JSON.stringify(jsrJson, null, 2) + "\n",
        "utf8",
      );
    }
  }

  if (!args.verify) {
    console.log(
      `Successfully processed version metadata for version: ${version}`,
    );
  }
}

function getArgs() {
  const args = {};
  for (let i = 0; i < process.argv.length; i++) {
    const arg = process.argv[i];
    if (arg === "--package-json") args.packageJson = process.argv[++i];
    if (arg === "--ts-out") args.tsOut = process.argv[++i];
    if (arg === "--jsr-json") args.jsrJson = process.argv[++i];
    if (arg === "--verify") args.verify = true;
    if (arg === "--debug-paths") args.debugPaths = true;
  }
  return args;
}

await main();
