name: Nix CI

on:
  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Run tests and generate coverage
        run: nix --extra-experimental-features 'nix-command flakes' develop --command make coverage-internal

      - name: Long LSAN test (fixed seed)
        run: nix --extra-experimental-features 'nix-command flakes' develop --command make thanatos-check-lsan-long-internal

      - name: Long UBSAN test (fixed seed)
        run: nix --extra-experimental-features 'nix-command flakes' develop --command make thanatos-check-ubsan-long-internal

      - name: Long ASAN test (fixed seed)
        run: nix --extra-experimental-features 'nix-command flakes' develop --command make thanatos-check-asan-long-internal

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.lcov,coverage-c.lcov
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Print WASM files
        run: |
          ls -lh wasm/
          nix --extra-experimental-features 'nix-command flakes' develop --command make print-wasm-internal

      - name: JSR dry run publish
        if: github.ref != 'refs/heads/main'
        run: nix run .#publish -- --dry-run
