name: Node.js CI
on: [push]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:22.14.0-slim

    steps:
      - uses: actions/checkout@v4

      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.7.0 --activate
          yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint
        run: yarn run lint

      - name: Run build
        run: yarn build

      - name: Run tests with coverage
        run: yarn test:coverage
