name: Publish Package to GitHub Packages

on:
  release:
    types: [released]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@maxdeliso'

      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.7.0 --activate
          yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint
        run: yarn run lint

      - name: Run build
        run: yarn build

      - name: Run tests with coverage
        run: yarn test:coverage

      - name: Debug environment
        run: |
          echo "Node version: $(node -v)"
          echo "Yarn version: $(yarn -v)"
          echo "NPM version: $(npm -v)"
          echo "HOME directory: $HOME"
          echo "Working directory: $(pwd)"
          echo "GitHub token available: ${{ secrets.GITHUB_TOKEN != '' }}"
          echo "Registry configuration:"
          npm config get registry
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish package with NPM
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
