name: Publish Package to GitHub Packages

on:
  release:
    types: [published, released, created, edited]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    container:
      image: node:22.14.0-slim

    steps:
      - uses: actions/checkout@v4

      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.7.0 --activate
          yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint
        run: yarn run lint

      - name: Run build
        run: yarn build

      - name: Run tests with coverage
        run: yarn test:coverage

      - name: Debug environment
        run: |
          echo "Node version: $(node -v)"
          echo "Yarn version: $(yarn -v)"
          echo "NPM version: $(npm -v)"
          echo "HOME directory: $HOME"
          echo "Working directory: $(pwd)"
          echo "GitHub token available: ${{ secrets.GITHUB_TOKEN != '' }}"
          echo "Registry configuration:"
          npm config get registry
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Setup for publishing
        run: |
          # Configure Yarn to use GitHub Packages
          yarn config set npmScopes.maxdeliso.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.maxdeliso.npmAlwaysAuth true
          yarn config set npmScopes.maxdeliso.npmAuthToken "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish package
        run: |
          echo "Attempting to publish with Yarn..."
          if ! yarn npm publish --access=public; then
            echo "Yarn publish failed, trying with npm directly..."
            npm publish --access=public
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
